import type { MarketScanResponse, ScannerResult } from '@/features/scanner/models/scannerModels';

const baseTechnical = {
  ticker: 'PETR4',
  analysisDate: '2026-08-04',
  timeframe: '1D',
  lastClose: 42.3,
  sma9: 41.2,
  sma21: 39.8,
  ema9: 41.6,
  ema21: 39.9,
  rsi9: 58.4,
  atr14: 1.24,
  adx14: 26.8,
  averageVolume20: 58200000,
  averageFinancialVolume20: 2450000000,
  relativeVolume20: 1.38,
  distanceFromSma21Percent: 6.28,
  return5DaysPercent: 2.1,
  return20DaysPercent: 8.7,
  distanceFromEma9Percent: 1.68,
  distanceFromEma21Percent: 6.02,
  highestHigh5: 43.1,
  highestHigh10: 44.2,
  highestHigh20: 44.2,
  lowestLow5: 40.6,
  lowestLow10: 39.1,
  lowestLow20: 36.8,
  recentHigh: 44.2,
  recentHighDate: '2026-07-31',
  recentLow: 39.1,
  recentLowDate: '2026-07-28',
  candlesSinceRecentHigh: 3,
  pullbackDepthPercent: 4.3,
  previousCandleHigh: 42.1,
  previousCandleLow: 40.7,
  previousCandleClose: 41.4,
  movingAverageSlope9: 0.42,
  movingAverageSlope21: 0.25,
  consolidationWidthPercent: 7.4,
  bullishVolumeAverage: 61100000,
  bearishVolumeAverage: 45500000,
  latestClosedCandleVolume: 67100000,
  previousClosedCandleVolume: 53100000,
  trend: 'UPTREND' as const,
};

const baseChecks = {
  closeAboveSma21: true,
  sma9AboveSma21: true,
  rsiInsideRange: true,
  adxAccepted: true,
  liquidityAccepted: true,
  historyAccepted: true,
};

const baseEntryChecks = {
  trendQualified: true,
  priceAboveSma21: true,
  ema9AboveEma21: true,
  adxAccepted: true,
  recentHighDetected: true,
  pullbackDepthAccepted: true,
  touchedShortAverage: true,
  sma21Preserved: true,
  rsiEntryRangeAccepted: true,
  closedAbovePreviousHigh: false,
  latestCloseAbovePreviousClose: true,
  latestCloseAboveEma9: true,
  bullishConfirmationCandle: true,
  previousLowPreserved: true,
  confirmationVolumeAccepted: true,
  breakoutAboveRecentHigh: false,
  breakoutVolumeAccepted: true,
  liquidityAccepted: true,
  breakoutEligible: true,
  latestCloseAboveEma21: true,
  breakoutRsiAccepted: true,
  breakoutAdxAccepted: true,
  breakoutExtensionAccepted: true,
  consolidationDetected: false,
  overextendedFromEma21: false,
  trendWeakening: false,
  ema9SlopeNegative: false,
  latestCloseBelowSma21: false,
  adxWeakening: false,
  latestSwingLowBelowPrevious: false,
  movingAveragesConverging: false,
  higherLowDetected: true,
  sufficientEntryHistory: true,
};

const baseBreakdown = {
  trend: 15,
  pullbackDepth: 15,
  averageTouch: 15,
  sma21Preserved: 10,
  rsi: 10,
  confirmationCandle: 15,
  higherLow: 10,
  volume: 5,
  distance: 5,
  breakout: 0,
  relativeVolume: 0,
  adx: 0,
  movingAverageSlope: 0,
  extension: 0,
  recentReturn: 0,
  total: 100,
};

function result(overrides: Partial<ScannerResult>): ScannerResult {
  return {
    ticker: 'PETR4',
    analysisDate: '2026-08-04',
    timeframe: '1D',
    lastClose: 42.3,
    currentPrice: 42.55,
    dataStatus: 'INTRADAY_PARTIAL',
    currentPartialCandle: {
      date: '2026-08-05',
      open: 42.3,
      high: 42.9,
      low: 41.8,
      close: 42.55,
      volume: 18800000,
      status: 'INTRADAY_PARTIAL',
      fetchedAt: '2026-08-05T12:51:00-03:00',
    },
    marketDataUpdatedAt: '2026-08-05T12:51:00-03:00',
    score: 92,
    status: 'QUALIFIED',
    trend: 'UPTREND',
    technicalAnalysis: baseTechnical,
    entryAnalysis: {
      status: 'ENTRY_READY',
      setupType: 'PULLBACK',
      confirmationStrength: 'MODERATE',
      score: 88,
      scoreBreakdown: { ...baseBreakdown, total: 88 },
      checks: baseEntryChecks,
      reasons: ['Moderate pullback confirmation: bullish close above EMA9 and previous close'],
      recentHigh: 44.2,
      recentLow: 39.1,
      pullbackDepthPercent: 4.3,
      distanceFromEma9Percent: 1.68,
      distanceFromEma21Percent: 6.02,
      candlesSinceRecentHigh: 3,
      consolidationWidthPercent: 7.4,
      nearestSupport: 39.1,
      nearestResistance: 44.2,
      recentHighBeforeLatest: 44.2,
      breakoutPercentAboveResistance: 0,
      breakoutConfirmed: false,
      pullbackDetected: true,
      pullbackConfirmed: true,
      overextended: false,
      sideways: false,
    },
    checks: baseChecks,
    reasons: ['Momentum qualified: mandatory momentum checks passed'],
    ...overrides,
  };
}

export const mockMarketScanResponse: MarketScanResponse = {
  scannedAt: '2026-08-05T12:51:00-03:00',
  strategy: 'MOMENTUM',
  discoveredCount: 350,
  eligibleCount: 144,
  analyzedCount: 142,
  qualifiedCount: 18,
  momentumQualifiedCount: 18,
  momentumWatchCount: 42,
  breakoutEligibleCount: 31,
  breakoutReadyCount: 4,
  pullbackReadyCount: 8,
  returnedCount: 6,
  totalExecutionDurationMillis: 22140,
  averageAnalysisDurationMillis: 156,
  providerRequestCount: 143,
  results: [
    result({ ticker: 'PETR4' }),
    result({
      ticker: 'VALE3',
      score: 89,
      entryAnalysis: {
        ...result({}).entryAnalysis!,
        status: 'PULLBACK_CONFIRMED',
        score: 76,
      },
    }),
    result({
      ticker: 'WEGE3',
      score: 86,
      lastClose: 38.7,
      currentPrice: 38.7,
      dataStatus: 'CLOSED',
      currentPartialCandle: null,
      entryAnalysis: {
        ...result({}).entryAnalysis!,
        status: 'WAIT_BREAKOUT',
        setupType: 'NONE',
        score: 54,
        sideways: true,
        pullbackDetected: false,
        pullbackConfirmed: false,
        reasons: [
          'Trend is qualified but price remains inside a consolidation range',
          'No breakout above recent resistance was confirmed',
        ],
      },
    }),
    result({
      ticker: 'PRIO3',
      score: 83,
      entryAnalysis: {
        ...result({}).entryAnalysis!,
        status: 'OVEREXTENDED',
        setupType: 'NONE',
        score: 43,
        overextended: true,
        reasons: ['Stock is overextended for a new swing entry'],
      },
    }),
    result({
      ticker: 'ABEV3',
      score: 73,
      entryAnalysis: {
        ...result({}).entryAnalysis!,
        status: 'WAIT_PULLBACK',
        setupType: 'NONE',
        score: 41,
        pullbackDetected: false,
      },
    }),
    result({
      ticker: 'CMIG4',
      score: 71,
      entryAnalysis: {
        ...result({}).entryAnalysis!,
        status: 'BREAKOUT_CONFIRMED',
        setupType: 'BREAKOUT',
        score: 79,
        breakoutConfirmed: true,
      },
    }),
  ],
  failures: [
    {
      ticker: 'INVALID3',
      errorCode: 'TICKER_NOT_FOUND',
      message: 'Ticker was not found by the market data provider',
    },
  ],
};
