package br.com.bauzin.market.panic.panicscanner.domain.analysis;

import java.math.BigDecimal;
import java.time.LocalDate;

/** Technical analysis snapshot consumed by scanner strategies. */
public record TechnicalAnalysis(
        String ticker,
        LocalDate analysisDate,
        String timeframe,
        BigDecimal lastClose,
        BigDecimal sma9,
        BigDecimal sma21,
        BigDecimal ema9,
        BigDecimal ema21,
        BigDecimal rsi9,
        BigDecimal atr14,
        BigDecimal adx14,
        BigDecimal averageVolume20,
        BigDecimal averageFinancialVolume20,
        BigDecimal relativeVolume20,
        BigDecimal distanceFromSma21Percent,
        BigDecimal return5DaysPercent,
        BigDecimal return20DaysPercent,
        BigDecimal distanceFromEma9Percent,
        BigDecimal distanceFromEma21Percent,
        BigDecimal highestHigh5,
        BigDecimal highestHigh10,
        BigDecimal highestHigh20,
        BigDecimal lowestLow5,
        BigDecimal lowestLow10,
        BigDecimal lowestLow20,
        BigDecimal recentHigh,
        LocalDate recentHighDate,
        BigDecimal recentLow,
        LocalDate recentLowDate,
        Integer candlesSinceRecentHigh,
        BigDecimal pullbackDepthPercent,
        BigDecimal previousCandleHigh,
        BigDecimal previousCandleLow,
        BigDecimal previousCandleClose,
        BigDecimal movingAverageSlope9,
        BigDecimal movingAverageSlope21,
        BigDecimal consolidationWidthPercent,
        BigDecimal bullishVolumeAverage,
        BigDecimal bearishVolumeAverage,
        BigDecimal latestClosedCandleVolume,
        BigDecimal previousClosedCandleVolume,
        Trend trend) {

    public TechnicalAnalysis(String ticker,
                             LocalDate analysisDate,
                             String timeframe,
                             BigDecimal lastClose,
                             BigDecimal sma9,
                             BigDecimal sma21,
                             BigDecimal rsi9,
                             BigDecimal averageFinancialVolume20,
                             Trend trend) {
        this(ticker,
                analysisDate,
                timeframe,
                lastClose,
                sma9,
                sma21,
                sma9,
                sma21,
                rsi9,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                averageFinancialVolume20,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                null,
                BigDecimal.ZERO,
                null,
                0,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                trend);
    }

    public TechnicalAnalysis(String ticker,
                             LocalDate analysisDate,
                             String timeframe,
                             BigDecimal lastClose,
                             BigDecimal sma9,
                             BigDecimal sma21,
                             BigDecimal ema9,
                             BigDecimal ema21,
                             BigDecimal rsi9,
                             BigDecimal atr14,
                             BigDecimal adx14,
                             BigDecimal averageVolume20,
                             BigDecimal averageFinancialVolume20,
                             BigDecimal relativeVolume20,
                             BigDecimal distanceFromSma21Percent,
                             BigDecimal return5DaysPercent,
                             BigDecimal return20DaysPercent,
                             BigDecimal highestHigh20,
                             BigDecimal lowestLow20,
                             Trend trend) {
        this(ticker,
                analysisDate,
                timeframe,
                lastClose,
                sma9,
                sma21,
                ema9,
                ema21,
                rsi9,
                atr14,
                adx14,
                averageVolume20,
                averageFinancialVolume20,
                relativeVolume20,
                distanceFromSma21Percent,
                return5DaysPercent,
                return20DaysPercent,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                highestHigh20,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                lowestLow20,
                highestHigh20,
                null,
                lowestLow20,
                null,
                0,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                BigDecimal.ZERO,
                trend);
    }
}
